---
# tasks file for k8s_worker
- name: Copy join command from Ansiblehost to the worker nodes.
  become: yes
  copy:
    src: "{{ k8s_join_command_file_path }}"
    dest: "{{ k8s_join_command_file_path }}"
    mode: 0777

- name: Join the Worker nodes to the cluster.
  shell: sh "{{ k8s_join_command_file_path }}" && touch $HOME/cluster_joined.lock
  args:
    chdir: $HOME
    creates: $HOME/cluster_joined.lock