---
# tasks file for k8s_master
- name: init by kubeadm
  shell: kubeadm init --image-repository=registry.aliyuncs.com/google_containers && touch $HOME/cluster_initialized.lock
  args:
    chdir: $HOME
    creates: $HOME/cluster_initialized.lock

- name: create .kube directory
  file:
    path: $HOME/.kube
    state: directory
    mode: 0755

- name: copy kubenetes admin config
  copy:
    src: /etc/kubernetes/admin.conf
    dest: $HOME/.kube/config
    mode: 0644
    force: yes
    remote_src: yes

- name: apply weave net as cni
  remote_user: root
  shell: kubectl apply -f "https://cloud.weave.works/k8s/net?k8s-version=$(kubectl version | base64 | tr -d '\n')"

- name: Get the token for joining the worker nodes
  shell: kubeadm token create  --print-join-command
  register: kubernetes_join_command

- name: print token
  debug:
    msg: "{{ kubernetes_join_command.stdout }}"

- name: Copy join command to local file.
  local_action: copy content="{{ kubernetes_join_command.stdout_lines[0] }}" dest="{{ k8s_join_command_file_path }}" mode=0666