---
# tasks file for master

# label node
- name: label master node
  shell: kubectl --overwrite=true label nodes {{ hostname }} ustoj=master

- name: Create a directory if it does not exist
  local_action:
    module: file
    path: /tmp/ustoj_master
    state: directory
    mode: '0755'

# generate app config
- name: make a config
  local_action:
    module: template
    src: configmap/ustoj_master.cm.j2
    dest: /tmp/ustoj_master/config_cm.yaml
    mode: '0644'
    force: yes

# generate app config
- name: make pv and pvc
  local_action:
    module: template
    src: pv/ustoj_master_pv.yaml.j2
    dest: /tmp/ustoj_master/pvc.yaml
    mode: '0644'
    force: yes

# generate app service
- name: make a service yaml
  local_action:
    module: template
    src: services/ustoj_master.yml.j2
    dest: /tmp/ustoj_master/service.yaml
    mode: '0644'
    force: yes

# generate app deployment
- name: make a deployment yaml
  local_action:
    module: template
    src: deployment/ustoj_master.yml.j2
    dest: /tmp/ustoj_master/deployment.yaml
    mode: '0644'
    force: yes

# apply all yaml
- name: apply deployment
  local_action:
    module: shell
    cmd: kubectl --kubeconfig {{ k8s_admin_config_local_dir }}/admin.conf apply -f /tmp/ustoj_master/config_cm.yaml -f /tmp/ustoj_master/pvc.yaml -f /tmp/ustoj_master/deployment.yaml -f /tmp/ustoj_master/service.yaml